"""add column family models

Revision ID: cd1a7648c2fd
Revises: aacdeb384f28
Create Date: 2024-03-15 14:59:41.451305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1a7648c2fd'
down_revision: Union[str, None] = 'aacdeb384f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('family', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'family')
    # ### end Alembic commands ###
